# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Sidelog"
description: > # this means to ignore newlines until "email:"
   sidelog best team ever

email: yereeyoo@gmil.com
#blog logo
logo: "/assets/images/"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/sidelog-winter.png"

name: 'yoo yeree'
author: 'yoo yeree'
author_image: ""

paginate:	5

#url: "http://myblog.***.***" # the base hostname & protocol for your site
#baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/side-log
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
